### ISSUE TITLE
Image server in Provider

### ISSUE THREAD

**Issue by forgetso** [prosopo/provider#175]
Datasets can contain images that are either stored locally or stored on a web resource. Locally stored images should be served via an image server when parsing a dataset.

Should the same image server be used to serve the images for CAPTCHA?

make provider run a separate file server, only enable if a flag has been passed. This means all local resources will be accessed via localhost/blah

**Comment by goastler** [comment]
We need to embed a http server in the provider to enable images that are stored on the provider's filesystem to be served over the web.
